package com.canteen.mapper;

import com.canteen.bean.Postreply;
import com.canteen.bean.PostreplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostreplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    long countByExample(PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int deleteByExample(PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer replyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int insert(Postreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int insertSelective(Postreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    List<Postreply> selectByExampleWithBLOBs(PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    List<Postreply> selectByExample(PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    Postreply selectByPrimaryKey(Integer replyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Postreply record, @Param("example") PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Postreply record, @Param("example") PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Postreply record, @Param("example") PostreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Postreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Postreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Postreply record);
}