package com.canteen.mapper;

import com.canteen.bean.Postlikes;
import com.canteen.bean.PostlikesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PostlikesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    long countByExample(PostlikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    int deleteByExample(PostlikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer likeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    int insert(Postlikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    int insertSelective(Postlikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    List<Postlikes> selectByExample(PostlikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    Postlikes selectByPrimaryKey(Integer likeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Postlikes record, @Param("example") PostlikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Postlikes record, @Param("example") PostlikesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Postlikes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Postlikes record);
}