package com.canteen.mapper;

import com.canteen.bean.Systemadmin;
import com.canteen.bean.SystemadminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemadminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    long countByExample(SystemadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    int deleteByExample(SystemadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    int insert(Systemadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    int insertSelective(Systemadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    List<Systemadmin> selectByExample(SystemadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    Systemadmin selectByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Systemadmin record, @Param("example") SystemadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Systemadmin record, @Param("example") SystemadminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Systemadmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Systemadmin record);
}