package com.canteen.bean;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table CanteenReviewReply
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Canteenreviewreply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenReviewReply.ReplyID
     *
     * @mbg.generated
     */
    private Integer replyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenReviewReply.CanteenReviewID
     *
     * @mbg.generated
     */
    private Integer canteenreviewid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenReviewReply.ManagerID
     *
     * @mbg.generated
     */
    private Integer managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenReviewReply.ReplyTime
     *
     * @mbg.generated
     */
    private Date replytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenReviewReply.ReplyContent
     *
     * @mbg.generated
     */
    private String replycontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenReviewReply.ReplyID
     *
     * @return the value of CanteenReviewReply.ReplyID
     *
     * @mbg.generated
     */
    public Integer getReplyid() {
        return replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenReviewReply.ReplyID
     *
     * @param replyid the value for CanteenReviewReply.ReplyID
     *
     * @mbg.generated
     */
    public void setReplyid(Integer replyid) {
        this.replyid = replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenReviewReply.CanteenReviewID
     *
     * @return the value of CanteenReviewReply.CanteenReviewID
     *
     * @mbg.generated
     */
    public Integer getCanteenreviewid() {
        return canteenreviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenReviewReply.CanteenReviewID
     *
     * @param canteenreviewid the value for CanteenReviewReply.CanteenReviewID
     *
     * @mbg.generated
     */
    public void setCanteenreviewid(Integer canteenreviewid) {
        this.canteenreviewid = canteenreviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenReviewReply.ManagerID
     *
     * @return the value of CanteenReviewReply.ManagerID
     *
     * @mbg.generated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenReviewReply.ManagerID
     *
     * @param managerid the value for CanteenReviewReply.ManagerID
     *
     * @mbg.generated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenReviewReply.ReplyTime
     *
     * @return the value of CanteenReviewReply.ReplyTime
     *
     * @mbg.generated
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenReviewReply.ReplyTime
     *
     * @param replytime the value for CanteenReviewReply.ReplyTime
     *
     * @mbg.generated
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenReviewReply.ReplyContent
     *
     * @return the value of CanteenReviewReply.ReplyContent
     *
     * @mbg.generated
     */
    public String getReplycontent() {
        return replycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenReviewReply.ReplyContent
     *
     * @param replycontent the value for CanteenReviewReply.ReplyContent
     *
     * @mbg.generated
     */
    public void setReplycontent(String replycontent) {
        this.replycontent = replycontent;
    }
}