package com.canteen.bean;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table CanteenManager
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Canteenmanager implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenManager.ManagerID
     *
     * @mbg.generated
     */
    private Integer managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenManager.ManagerName
     *
     * @mbg.generated
     */
    private String managername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenManager.Gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenManager.ManagerPassword
     *
     * @mbg.generated
     */
    private String managerpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CanteenManager.CanteenID
     *
     * @mbg.generated
     */
    private Integer canteenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenManager.ManagerID
     *
     * @return the value of CanteenManager.ManagerID
     *
     * @mbg.generated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenManager.ManagerID
     *
     * @param managerid the value for CanteenManager.ManagerID
     *
     * @mbg.generated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenManager.ManagerName
     *
     * @return the value of CanteenManager.ManagerName
     *
     * @mbg.generated
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenManager.ManagerName
     *
     * @param managername the value for CanteenManager.ManagerName
     *
     * @mbg.generated
     */
    public void setManagername(String managername) {
        this.managername = managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenManager.Gender
     *
     * @return the value of CanteenManager.Gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenManager.Gender
     *
     * @param gender the value for CanteenManager.Gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenManager.ManagerPassword
     *
     * @return the value of CanteenManager.ManagerPassword
     *
     * @mbg.generated
     */
    public String getManagerpassword() {
        return managerpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenManager.ManagerPassword
     *
     * @param managerpassword the value for CanteenManager.ManagerPassword
     *
     * @mbg.generated
     */
    public void setManagerpassword(String managerpassword) {
        this.managerpassword = managerpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CanteenManager.CanteenID
     *
     * @return the value of CanteenManager.CanteenID
     *
     * @mbg.generated
     */
    public Integer getCanteenid() {
        return canteenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CanteenManager.CanteenID
     *
     * @param canteenid the value for CanteenManager.CanteenID
     *
     * @mbg.generated
     */
    public void setCanteenid(Integer canteenid) {
        this.canteenid = canteenid;
    }
}