package com.canteen.bean;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Canteen
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Canteen implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Canteen.CanteenID
     *
     * @mbg.generated
     */
    private Integer canteenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Canteen.CanteenName
     *
     * @mbg.generated
     */
    private String canteenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Canteen.Location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Canteen.StartTime
     *
     * @mbg.generated
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Canteen.EndTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Canteen
     *
     * @mbg.generated
     */



    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Canteen.Description
     *
     * @return the value of Canteen.Description
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Canteen.CanteenID
     *
     * @return the value of Canteen.CanteenID
     *
     * @mbg.generated
     */
    public Integer getCanteenid() {
        return canteenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Canteen.CanteenID
     *
     * @param canteenid the value for Canteen.CanteenID
     *
     * @mbg.generated
     */
    public void setCanteenid(Integer canteenid) {
        this.canteenid = canteenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Canteen.CanteenName
     *
     * @return the value of Canteen.CanteenName
     *
     * @mbg.generated
     */
    public String getCanteenname() {
        return canteenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Canteen.CanteenName
     *
     * @param canteenname the value for Canteen.CanteenName
     *
     * @mbg.generated
     */
    public void setCanteenname(String canteenname) {
        this.canteenname = canteenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Canteen.Location
     *
     * @return the value of Canteen.Location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Canteen.Location
     *
     * @param location the value for Canteen.Location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Canteen.StartTime
     *
     * @return the value of Canteen.StartTime
     *
     * @mbg.generated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Canteen.StartTime
     *
     * @param starttime the value for Canteen.StartTime
     *
     * @mbg.generated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Canteen.EndTime
     *
     * @return the value of Canteen.EndTime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Canteen.EndTime
     *
     * @param endtime the value for Canteen.EndTime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }


    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Canteen.Description
     *
     * @param description the value for Canteen.Description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }
}