package com.canteen.bean;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table CommunityPost
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Communitypost implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CommunityPost.PostID
     *
     * @mbg.generated
     */
    private Integer postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CommunityPost.UserID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CommunityPost.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CommunityPost.ImageURL
     *
     * @mbg.generated
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CommunityPost.PostTime
     *
     * @mbg.generated
     */
    private Date posttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CommunityPost.Content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CommunityPost
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CommunityPost.PostID
     *
     * @return the value of CommunityPost.PostID
     *
     * @mbg.generated
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CommunityPost.PostID
     *
     * @param postid the value for CommunityPost.PostID
     *
     * @mbg.generated
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CommunityPost.UserID
     *
     * @return the value of CommunityPost.UserID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CommunityPost.UserID
     *
     * @param userid the value for CommunityPost.UserID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CommunityPost.Title
     *
     * @return the value of CommunityPost.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CommunityPost.Title
     *
     * @param title the value for CommunityPost.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CommunityPost.ImageURL
     *
     * @return the value of CommunityPost.ImageURL
     *
     * @mbg.generated
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CommunityPost.ImageURL
     *
     * @param imageurl the value for CommunityPost.ImageURL
     *
     * @mbg.generated
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CommunityPost.PostTime
     *
     * @return the value of CommunityPost.PostTime
     *
     * @mbg.generated
     */
    public Date getPosttime() {
        return posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CommunityPost.PostTime
     *
     * @param posttime the value for CommunityPost.PostTime
     *
     * @mbg.generated
     */
    public void setPosttime(Date posttime) {
        this.posttime = posttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CommunityPost.Content
     *
     * @return the value of CommunityPost.Content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CommunityPost.Content
     *
     * @param content the value for CommunityPost.Content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}