package com.canteen.bean;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table DishReview
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Dishreview implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DishReview.DishReviewID
     *
     * @mbg.generated
     */
    private Integer dishreviewid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DishReview.UserID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DishReview.DishID
     *
     * @mbg.generated
     */
    private Integer dishid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DishReview.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DishReview.ImageURL
     *
     * @mbg.generated
     */
    private String imageurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DishReview.ReviewTime
     *
     * @mbg.generated
     */
    private Date reviewtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DishReview.Rating
     *
     * @mbg.generated
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DishReview.Content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DishReview
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DishReview.DishReviewID
     *
     * @return the value of DishReview.DishReviewID
     *
     * @mbg.generated
     */
    public Integer getDishreviewid() {
        return dishreviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DishReview.DishReviewID
     *
     * @param dishreviewid the value for DishReview.DishReviewID
     *
     * @mbg.generated
     */
    public void setDishreviewid(Integer dishreviewid) {
        this.dishreviewid = dishreviewid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DishReview.UserID
     *
     * @return the value of DishReview.UserID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DishReview.UserID
     *
     * @param userid the value for DishReview.UserID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DishReview.DishID
     *
     * @return the value of DishReview.DishID
     *
     * @mbg.generated
     */
    public Integer getDishid() {
        return dishid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DishReview.DishID
     *
     * @param dishid the value for DishReview.DishID
     *
     * @mbg.generated
     */
    public void setDishid(Integer dishid) {
        this.dishid = dishid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DishReview.Title
     *
     * @return the value of DishReview.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DishReview.Title
     *
     * @param title the value for DishReview.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DishReview.ImageURL
     *
     * @return the value of DishReview.ImageURL
     *
     * @mbg.generated
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DishReview.ImageURL
     *
     * @param imageurl the value for DishReview.ImageURL
     *
     * @mbg.generated
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DishReview.ReviewTime
     *
     * @return the value of DishReview.ReviewTime
     *
     * @mbg.generated
     */
    public Date getReviewtime() {
        return reviewtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DishReview.ReviewTime
     *
     * @param reviewtime the value for DishReview.ReviewTime
     *
     * @mbg.generated
     */
    public void setReviewtime(Date reviewtime) {
        this.reviewtime = reviewtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DishReview.Rating
     *
     * @return the value of DishReview.Rating
     *
     * @mbg.generated
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DishReview.Rating
     *
     * @param rating the value for DishReview.Rating
     *
     * @mbg.generated
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DishReview.Content
     *
     * @return the value of DishReview.Content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DishReview.Content
     *
     * @param content the value for DishReview.Content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }
}