package com.canteen.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class DishExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Dish
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Dish
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Dish
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public DishExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Dish
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDishidIsNull() {
            addCriterion("DishID is null");
            return (Criteria) this;
        }

        public Criteria andDishidIsNotNull() {
            addCriterion("DishID is not null");
            return (Criteria) this;
        }

        public Criteria andDishidEqualTo(Integer value) {
            addCriterion("DishID =", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidNotEqualTo(Integer value) {
            addCriterion("DishID <>", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidGreaterThan(Integer value) {
            addCriterion("DishID >", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidGreaterThanOrEqualTo(Integer value) {
            addCriterion("DishID >=", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidLessThan(Integer value) {
            addCriterion("DishID <", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidLessThanOrEqualTo(Integer value) {
            addCriterion("DishID <=", value, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidIn(List<Integer> values) {
            addCriterion("DishID in", values, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidNotIn(List<Integer> values) {
            addCriterion("DishID not in", values, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidBetween(Integer value1, Integer value2) {
            addCriterion("DishID between", value1, value2, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishidNotBetween(Integer value1, Integer value2) {
            addCriterion("DishID not between", value1, value2, "dishid");
            return (Criteria) this;
        }

        public Criteria andDishnameIsNull() {
            addCriterion("DishName is null");
            return (Criteria) this;
        }

        public Criteria andDishnameIsNotNull() {
            addCriterion("DishName is not null");
            return (Criteria) this;
        }

        public Criteria andDishnameEqualTo(String value) {
            addCriterion("DishName =", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameNotEqualTo(String value) {
            addCriterion("DishName <>", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameGreaterThan(String value) {
            addCriterion("DishName >", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameGreaterThanOrEqualTo(String value) {
            addCriterion("DishName >=", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameLessThan(String value) {
            addCriterion("DishName <", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameLessThanOrEqualTo(String value) {
            addCriterion("DishName <=", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameLike(String value) {
            addCriterion("DishName like", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameNotLike(String value) {
            addCriterion("DishName not like", value, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameIn(List<String> values) {
            addCriterion("DishName in", values, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameNotIn(List<String> values) {
            addCriterion("DishName not in", values, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameBetween(String value1, String value2) {
            addCriterion("DishName between", value1, value2, "dishname");
            return (Criteria) this;
        }

        public Criteria andDishnameNotBetween(String value1, String value2) {
            addCriterion("DishName not between", value1, value2, "dishname");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("Price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("Price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("Price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("Price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("Price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("Price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("Price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("Price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPromotepriceIsNull() {
            addCriterion("PromotePrice is null");
            return (Criteria) this;
        }

        public Criteria andPromotepriceIsNotNull() {
            addCriterion("PromotePrice is not null");
            return (Criteria) this;
        }

        public Criteria andPromotepriceEqualTo(BigDecimal value) {
            addCriterion("PromotePrice =", value, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andPromotepriceNotEqualTo(BigDecimal value) {
            addCriterion("PromotePrice <>", value, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andPromotepriceGreaterThan(BigDecimal value) {
            addCriterion("PromotePrice >", value, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andPromotepriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PromotePrice >=", value, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andPromotepriceLessThan(BigDecimal value) {
            addCriterion("PromotePrice <", value, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andPromotepriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PromotePrice <=", value, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andPromotepriceIn(List<BigDecimal> values) {
            addCriterion("PromotePrice in", values, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andPromotepriceNotIn(List<BigDecimal> values) {
            addCriterion("PromotePrice not in", values, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andPromotepriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PromotePrice between", value1, value2, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andPromotepriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PromotePrice not between", value1, value2, "promoteprice");
            return (Criteria) this;
        }

        public Criteria andDishstyleIsNull() {
            addCriterion("DishStyle is null");
            return (Criteria) this;
        }

        public Criteria andDishstyleIsNotNull() {
            addCriterion("DishStyle is not null");
            return (Criteria) this;
        }

        public Criteria andDishstyleEqualTo(String value) {
            addCriterion("DishStyle =", value, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleNotEqualTo(String value) {
            addCriterion("DishStyle <>", value, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleGreaterThan(String value) {
            addCriterion("DishStyle >", value, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleGreaterThanOrEqualTo(String value) {
            addCriterion("DishStyle >=", value, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleLessThan(String value) {
            addCriterion("DishStyle <", value, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleLessThanOrEqualTo(String value) {
            addCriterion("DishStyle <=", value, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleLike(String value) {
            addCriterion("DishStyle like", value, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleNotLike(String value) {
            addCriterion("DishStyle not like", value, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleIn(List<String> values) {
            addCriterion("DishStyle in", values, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleNotIn(List<String> values) {
            addCriterion("DishStyle not in", values, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleBetween(String value1, String value2) {
            addCriterion("DishStyle between", value1, value2, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andDishstyleNotBetween(String value1, String value2) {
            addCriterion("DishStyle not between", value1, value2, "dishstyle");
            return (Criteria) this;
        }

        public Criteria andCanteenidIsNull() {
            addCriterion("CanteenID is null");
            return (Criteria) this;
        }

        public Criteria andCanteenidIsNotNull() {
            addCriterion("CanteenID is not null");
            return (Criteria) this;
        }

        public Criteria andCanteenidEqualTo(Integer value) {
            addCriterion("CanteenID =", value, "canteenid");
            return (Criteria) this;
        }

        public Criteria andCanteenidNotEqualTo(Integer value) {
            addCriterion("CanteenID <>", value, "canteenid");
            return (Criteria) this;
        }

        public Criteria andCanteenidGreaterThan(Integer value) {
            addCriterion("CanteenID >", value, "canteenid");
            return (Criteria) this;
        }

        public Criteria andCanteenidGreaterThanOrEqualTo(Integer value) {
            addCriterion("CanteenID >=", value, "canteenid");
            return (Criteria) this;
        }

        public Criteria andCanteenidLessThan(Integer value) {
            addCriterion("CanteenID <", value, "canteenid");
            return (Criteria) this;
        }

        public Criteria andCanteenidLessThanOrEqualTo(Integer value) {
            addCriterion("CanteenID <=", value, "canteenid");
            return (Criteria) this;
        }

        public Criteria andCanteenidIn(List<Integer> values) {
            addCriterion("CanteenID in", values, "canteenid");
            return (Criteria) this;
        }

        public Criteria andCanteenidNotIn(List<Integer> values) {
            addCriterion("CanteenID not in", values, "canteenid");
            return (Criteria) this;
        }

        public Criteria andCanteenidBetween(Integer value1, Integer value2) {
            addCriterion("CanteenID between", value1, value2, "canteenid");
            return (Criteria) this;
        }

        public Criteria andCanteenidNotBetween(Integer value1, Integer value2) {
            addCriterion("CanteenID not between", value1, value2, "canteenid");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("Description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("Description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("Description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("Description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("Description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("Description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("Description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("Description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("Description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("Description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("Description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("Description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andImagefilenameIsNull() {
            addCriterion("ImageFileName is null");
            return (Criteria) this;
        }

        public Criteria andImagefilenameIsNotNull() {
            addCriterion("ImageFileName is not null");
            return (Criteria) this;
        }

        public Criteria andImagefilenameEqualTo(String value) {
            addCriterion("ImageFileName =", value, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameNotEqualTo(String value) {
            addCriterion("ImageFileName <>", value, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameGreaterThan(String value) {
            addCriterion("ImageFileName >", value, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameGreaterThanOrEqualTo(String value) {
            addCriterion("ImageFileName >=", value, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameLessThan(String value) {
            addCriterion("ImageFileName <", value, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameLessThanOrEqualTo(String value) {
            addCriterion("ImageFileName <=", value, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameLike(String value) {
            addCriterion("ImageFileName like", value, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameNotLike(String value) {
            addCriterion("ImageFileName not like", value, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameIn(List<String> values) {
            addCriterion("ImageFileName in", values, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameNotIn(List<String> values) {
            addCriterion("ImageFileName not in", values, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameBetween(String value1, String value2) {
            addCriterion("ImageFileName between", value1, value2, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andImagefilenameNotBetween(String value1, String value2) {
            addCriterion("ImageFileName not between", value1, value2, "imagefilename");
            return (Criteria) this;
        }

        public Criteria andIfrecommendIsNull() {
            addCriterion("IfRecommend is null");
            return (Criteria) this;
        }

        public Criteria andIfrecommendIsNotNull() {
            addCriterion("IfRecommend is not null");
            return (Criteria) this;
        }

        public Criteria andIfrecommendEqualTo(Boolean value) {
            addCriterion("IfRecommend =", value, "ifrecommend");
            return (Criteria) this;
        }

        public Criteria andIfrecommendNotEqualTo(Boolean value) {
            addCriterion("IfRecommend <>", value, "ifrecommend");
            return (Criteria) this;
        }

        public Criteria andIfrecommendGreaterThan(Boolean value) {
            addCriterion("IfRecommend >", value, "ifrecommend");
            return (Criteria) this;
        }

        public Criteria andIfrecommendGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IfRecommend >=", value, "ifrecommend");
            return (Criteria) this;
        }

        public Criteria andIfrecommendLessThan(Boolean value) {
            addCriterion("IfRecommend <", value, "ifrecommend");
            return (Criteria) this;
        }

        public Criteria andIfrecommendLessThanOrEqualTo(Boolean value) {
            addCriterion("IfRecommend <=", value, "ifrecommend");
            return (Criteria) this;
        }

        public Criteria andIfrecommendIn(List<Boolean> values) {
            addCriterion("IfRecommend in", values, "ifrecommend");
            return (Criteria) this;
        }

        public Criteria andIfrecommendNotIn(List<Boolean> values) {
            addCriterion("IfRecommend not in", values, "ifrecommend");
            return (Criteria) this;
        }

        public Criteria andIfrecommendBetween(Boolean value1, Boolean value2) {
            addCriterion("IfRecommend between", value1, value2, "ifrecommend");
            return (Criteria) this;
        }

        public Criteria andIfrecommendNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IfRecommend not between", value1, value2, "ifrecommend");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Dish
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Dish
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}