package com.canteen.bean;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PostReply
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Postreply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PostReply.ReplyID
     *
     * @mbg.generated
     */
    private Integer replyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PostReply.PostID
     *
     * @mbg.generated
     */
    private Integer postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PostReply.UserID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PostReply.ReplyTime
     *
     * @mbg.generated
     */
    private Date replytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PostReply.ReplyContent
     *
     * @mbg.generated
     */
    private String replycontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PostReply
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PostReply.ReplyID
     *
     * @return the value of PostReply.ReplyID
     *
     * @mbg.generated
     */
    public Integer getReplyid() {
        return replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PostReply.ReplyID
     *
     * @param replyid the value for PostReply.ReplyID
     *
     * @mbg.generated
     */
    public void setReplyid(Integer replyid) {
        this.replyid = replyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PostReply.PostID
     *
     * @return the value of PostReply.PostID
     *
     * @mbg.generated
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PostReply.PostID
     *
     * @param postid the value for PostReply.PostID
     *
     * @mbg.generated
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PostReply.UserID
     *
     * @return the value of PostReply.UserID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PostReply.UserID
     *
     * @param userid the value for PostReply.UserID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PostReply.ReplyTime
     *
     * @return the value of PostReply.ReplyTime
     *
     * @mbg.generated
     */
    public Date getReplytime() {
        return replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PostReply.ReplyTime
     *
     * @param replytime the value for PostReply.ReplyTime
     *
     * @mbg.generated
     */
    public void setReplytime(Date replytime) {
        this.replytime = replytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PostReply.ReplyContent
     *
     * @return the value of PostReply.ReplyContent
     *
     * @mbg.generated
     */
    public String getReplycontent() {
        return replycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PostReply.ReplyContent
     *
     * @param replycontent the value for PostReply.ReplyContent
     *
     * @mbg.generated
     */
    public void setReplycontent(String replycontent) {
        this.replycontent = replycontent;
    }
}