package com.canteen.bean;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table PostLikes
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Postlikes implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PostLikes.LikeID
     *
     * @mbg.generated
     */
    private Integer likeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PostLikes.PostID
     *
     * @mbg.generated
     */
    private Integer postid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PostLikes.UserID
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PostLikes
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PostLikes.LikeID
     *
     * @return the value of PostLikes.LikeID
     *
     * @mbg.generated
     */
    public Integer getLikeid() {
        return likeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PostLikes.LikeID
     *
     * @param likeid the value for PostLikes.LikeID
     *
     * @mbg.generated
     */
    public void setLikeid(Integer likeid) {
        this.likeid = likeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PostLikes.PostID
     *
     * @return the value of PostLikes.PostID
     *
     * @mbg.generated
     */
    public Integer getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PostLikes.PostID
     *
     * @param postid the value for PostLikes.PostID
     *
     * @mbg.generated
     */
    public void setPostid(Integer postid) {
        this.postid = postid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PostLikes.UserID
     *
     * @return the value of PostLikes.UserID
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PostLikes.UserID
     *
     * @param userid the value for PostLikes.UserID
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}