package com.canteen.bean;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table SystemAdmin
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Systemadmin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemAdmin.Adminid
     *
     * @mbg.generated
     */
    private Integer adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemAdmin.Adminname
     *
     * @mbg.generated
     */
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SystemAdmin.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SystemAdmin
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemAdmin.Adminid
     *
     * @return the value of SystemAdmin.Adminid
     *
     * @mbg.generated
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemAdmin.Adminid
     *
     * @param adminid the value for SystemAdmin.Adminid
     *
     * @mbg.generated
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemAdmin.Adminname
     *
     * @return the value of SystemAdmin.Adminname
     *
     * @mbg.generated
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemAdmin.Adminname
     *
     * @param adminname the value for SystemAdmin.Adminname
     *
     * @mbg.generated
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SystemAdmin.password
     *
     * @return the value of SystemAdmin.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SystemAdmin.password
     *
     * @param password the value for SystemAdmin.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }
}