package com.canteen.dao;

import com.canteen.bean.Canteenreviewreply;
import com.canteen.bean.CanteenreviewreplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CanteenreviewreplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    long countByExample(CanteenreviewreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int deleteByExample(CanteenreviewreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer replyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int insert(Canteenreviewreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int insertSelective(Canteenreviewreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    List<Canteenreviewreply> selectByExampleWithBLOBs(CanteenreviewreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    List<Canteenreviewreply> selectByExample(CanteenreviewreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    Canteenreviewreply selectByPrimaryKey(Integer replyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Canteenreviewreply record, @Param("example") CanteenreviewreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Canteenreviewreply record, @Param("example") CanteenreviewreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Canteenreviewreply record, @Param("example") CanteenreviewreplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Canteenreviewreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Canteenreviewreply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReviewReply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Canteenreviewreply record);
}