package com.canteen.dao;

import com.canteen.bean.Canteenmanager;
import com.canteen.bean.CanteenmanagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CanteenmanagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    long countByExample(CanteenmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    int deleteByExample(CanteenmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer managerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    int insert(Canteenmanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    int insertSelective(Canteenmanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    List<Canteenmanager> selectByExample(CanteenmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    Canteenmanager selectByPrimaryKey(Integer managerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Canteenmanager record, @Param("example") CanteenmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Canteenmanager record, @Param("example") CanteenmanagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Canteenmanager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenManager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Canteenmanager record);
}