package com.canteen.dao;

import com.canteen.bean.Canteenreview;
import com.canteen.bean.CanteenreviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CanteenreviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    long countByExample(CanteenreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int deleteByExample(CanteenreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer canteenreviewid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int insert(Canteenreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int insertSelective(Canteenreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    List<Canteenreview> selectByExampleWithBLOBs(CanteenreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    List<Canteenreview> selectByExample(CanteenreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    Canteenreview selectByPrimaryKey(Integer canteenreviewid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Canteenreview record, @Param("example") CanteenreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Canteenreview record, @Param("example") CanteenreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Canteenreview record, @Param("example") CanteenreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Canteenreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Canteenreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CanteenReview
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Canteenreview record);
}